version: '3.8'

services:
  frontend:
    container_name: moc_2025_fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3006/api}
      - NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV:-production}
    volumes:
      - .:/app
        #- /app/node_modules
        #- /app/.next
    command: "yarn start"
    restart: unless-stopped

# networks:
#   default:
#     name: moc_network
#     external: true