version: '3.8'

services:
  frontend:
    container_name: moc_2025_fe_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3006/api}
      - NEXT_PUBLIC_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: yarn dev
    restart: unless-stopped

networks:
  default:
    name: moc_network
    external: true